server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/job-agent}
    session:
      tracking-modes: cookie
  tomcat:
    max-swallow-size: ${MAX_SWALLOW_SIZE:5MB}   # maximum size of the request body/payload
    max-http-form-post-size: ${MAX_HTTP_FORM_POST_SIZE:5MB}  # maximum size of the request body/payload

logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    '[org.springframework]': ${LOGGING_LEVEL_SPRING:INFO}
    '[org.quartz]': ${LOGGING_LEVEL_QUARTZ:INFO}
  file:
    name: ${LOGGING_FILE_NAME:/${application.name}.log}
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: /archived/${application.name}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: true
      total-size-cap: 2GB
      max-file-size: 10MB
      max-history: 7
spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: ${APP_NAME:${application.name}-${spring.profiles.active}}

springdoc:
  enabled: ${API_DOCS_ENABLED:true}
  api-docs:
    enabled: ${springdoc.enabled:true}
  swagger-ui:
    enabled:  ${springdoc.enabled:true}
  version: ${API_DOCS_VERSION:${application.version}}
  name: ${API_DOCS_NAME:${spring.application.name}}
  description: ${API_DOCS_DESCRIPTION:${application.description}}


